# Based on this article https://dev.to/rahul_suryash/steps-to-build-binary-executables-for-python-code-with-github-actions-4k92

name: Build and Release Executables

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version (e.g., v1.0.0)"
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
  
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.7'
  
      - name: Install dependencies
        run: pip install -r requirements.txt
  
      - name: Build executable
        run: pyinstaller --onefile main.py

      - name: Current directory
        run: ls dist/ -l
  
      - name: Rename executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/app.exe dist/app-windows.exe
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            mv dist/app dist/app-linux
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/app dist/app-macos
          fi
        shell: bash
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Download a Build Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          merge-multiple: true

      - name: Make files executable (Linux/Mac)
        run: chmod +x app-* || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
          files: |
            app-linux
            app-windows.exe
            app-macos

    
